project:
  type: website
  output-dir: .

website:
  title: "G2S Analytics"
  navbar:
    background: light
    left:
      - text: Inicio
        href: index.qmd
      - text: Proyectos
        href: proyectos.qmd
      - text: G2S Territorial Insights
        href: territorial_insights.qmd
      - text: CV (ES)
        href: cv.qmd
      - text: CV (EN)
        href: cv_en.qmd
    right:
      - text: Contacto
        href: mailto:cargingarsan@gmail.com

  page-footer:
    left: "© 2026 G2S Analytics"
    right: "Análisis cuantitativo aplicado"

format:
  html:
    theme: flatly
    toc: false
    page-layout: full
